[package]
name = "iroh-util"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
description = "Utilities for iroh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
cid.workspace = true
config.workspace = true
ctrlc.workspace = true
dirs-next.workspace = true
futures.workspace = true
humansize.workspace = true
rlimit.workspace = true
serde = { workspace = true, features = ["derive"] }
sysinfo.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
temp-env.workspace = true
testdir.workspace = true

[target.'cfg(unix)'.dev-dependencies]
nix.workspace = true
