[package]
name = "iroh-util"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
description = "Utilities for iroh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
cid.workspace = true

[dev-dependencies]
temp-env.workspace = true
testdir.workspace = true

[target.'cfg(unix)'.dev-dependencies]
nix.workspace = true
