apiVersion: "keramik.3box.io/v1alpha1"
kind: Network
metadata:
  name: dev
spec:
  replicas: 5
  cas:
    image: ceramicnetwork/ceramic-anchor-service:c56be4a3c0bbda012f4b08347e192caf5c405936
  ceramic:
    ipfs:
      kind: rust
      image: 3box/ceramic-one:dev
      imagePullPolicy: IfNotPresent
