apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: otel
spec:
  podMetricsEndpoints:
    - interval: 10s
      path: /metrics
      targetPort: 9465
  selector:
    matchLabels:
      app: otel
  podTargetLabels:
    - affinity
    - storageClass
    - scenario
    - simulation
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ceramic
spec:
  podMetricsEndpoints:
    - interval: 10s
      path: /metrics
      targetPort: 9464
  selector:
    matchLabels:
      app: ceramic
  podTargetLabels:
    - affinity
    - scenario
    - simulation
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ceramic-one
spec:
  podMetricsEndpoints:
    - interval: 10s
      path: /metrics
      targetPort: 9465
  selector:
    matchLabels:
      app: ceramic
  podTargetLabels:
    - affinity
    - scenario
    - simulation
