apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: otel
spec:
  podMetricsEndpoints:
  - interval: 10s
    path: /metrics
    targetPort: 9465
  selector:
    matchLabels:
      app: otel
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ceramic
spec:
  podMetricsEndpoints:
  - interval: 10s
    path: /metrics
    targetPort: 9464
  selector:
    matchLabels:
      app: ceramic
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ceramic-one
spec:
  podMetricsEndpoints:
  - interval: 10s
    path: /metrics
    targetPort: 9465
  selector:
    matchLabels:
      app: ceramic