---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nightly-performance
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch", "update", "watch"]
- apiGroups: ["keramik.3box.io"]
  resources: ["networks", "simulations"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["podmonitors"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nightly-performance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nightly-performance
subjects:
  - kind: ServiceAccount
    name: nightly-performance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nightly-performance