
[package]
name = "ceramic-pipeline"
description = "Pipeline of transformations on Ceramic Events"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
arrow-schema.workspace = true
arrow.workspace = true
async-stream.workspace = true
async-trait.workspace = true
ceramic-core.workspace = true
ceramic-event.workspace = true
cid.workspace = true
datafusion.workspace = true
datafusion-functions-json = "0.43.0"
expect-test.workspace = true
futures.workspace = true
int-enum.workspace = true
ipld-core.workspace = true
json-patch = "3.0.1"
object_store.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
parking_lot = "0.12.3"

[dev-dependencies]
test-log = "0.2.16"
ceramic-arrow-test.workspace = true
mockall.workspace = true
