[package]
name = "ceramic-service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
ceramic-api.workspace = true
ceramic-car.workspace = true
ceramic-core.workspace = true
ceramic-event.workspace = true
ceramic-store.workspace = true
cid.workspace = true
futures.workspace = true
hex.workspace = true
ipld-core.workspace = true
iroh-bitswap.workspace = true
multibase.workspace = true
multihash-codetable.workspace = true
multihash-derive.workspace = true
recon.workspace = true
serde.workspace = true
serde_ipld_dagcbor.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
expect-test.workspace = true
ipld-core.workspace = true
multibase.workspace = true
paste = "1.0"
rand.workspace = true
serde.workspace = true
serde_ipld_dagcbor.workspace = true
test-log.workspace = true
tmpdir.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
