apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-performance
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: affinity
              configMap:
                name: affinity
          containers:
            - name: nightly-performance
              volumeMounts:
                - name: affinity
                  mountPath: /affinity
