[package]
name = "ceramic-validation"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
ceramic-core.workspace = true
ceramic-event.workspace = true
chrono.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
ipld-core.workspace = true
k256.workspace = true
lru.workspace = true
multibase.workspace = true
multihash-codetable.workspace = true
once_cell.workspace = true
p256.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_ipld_dagcbor.workspace = true
sha3.workspace = true
ssi.workspace = true
tokio.workspace = true
tracing.workspace = true
unsigned-varint.workspace = true
# will probably need contract and signer-local features for self anchoring
alloy = { version = "0.4", features = ["k256", "provider-http", "rpc-types"] }

[dev-dependencies]
ceramic-car.workspace = true
tracing.workspace = true
test-log.workspace = true
# did-pkh = "0.2.1"
# did-method-key = "0.2.2"
# ssi-dids = "0.1.1"
