[package]
name = "ceramic-validation"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy.workspace = true
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
ceramic-core.workspace = true
ceramic-event.workspace = true
chrono.workspace = true
ed25519-dalek.workspace = true
ipld-core.workspace = true
k256.workspace = true
multibase.workspace = true
multihash-codetable.workspace = true
once_cell.workspace = true
p256.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_ipld_dagcbor.workspace = true
sha3.workspace = true
ssi.workspace = true
tokio.workspace = true
tracing.workspace = true
unsigned-varint.workspace = true

[dev-dependencies]
ceramic-car.workspace = true
tracing.workspace = true
test-log.workspace = true
