[package]
name = "ceramic-validation"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
ceramic-core.workspace = true
ceramic-event.workspace = true
chrono.workspace = true
ed25519-dalek.workspace = true
ipld-core.workspace = true
k256.workspace = true
lru.workspace = true
multibase.workspace = true
multihash-codetable.workspace = true
once_cell.workspace = true
p256.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_ipld_dagcbor.workspace = true
sha3.workspace = true
ssi.workspace = true
tokio.workspace = true
tracing.workspace = true
unsigned-varint.workspace = true
# TODO: workspace 
# hoku_provider = { git = "https://github.com/hokunet/rust-hoku.git", branch = "main" }
# hoku_sdk = { git = "https://github.com/hokunet/rust-hoku.git", branch = "main" }
hoku_provider = { path = "../../hoku/rust-hoku/provider" }
hoku_sdk = { path = "../../hoku/rust-hoku/sdk" }
hoku_signer = { git = "https://github.com/hokunet/rust-hoku.git", branch = "main" }
# will probably need contract and signer-local features for self anchoring
alloy = { version = "0.4", features = ["k256", "provider-http", "rpc-types"] }

[dev-dependencies]
ceramic-car.workspace = true
tracing.workspace = true
test-log.workspace = true
