[package]
name = "ceramic-anchor-service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ceramic-anchor-tree.workspace = true
ceramic-anchor-tx.workspace = true