[package]
name = "ceramic-anchor-service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
ceramic-anchor-tree.workspace = true
ceramic-anchor-tx.workspace = true
ceramic-core.workspace = true
ceramic-store.workspace = true
cid.workspace = true
expect-test = "1.5.0"
hex.workspace = true
ipld-core.workspace = true
multihash-codetable.workspace = true
jsonwebtoken = "9.3.0"
rand.workspace = true
serde.workspace = true
serde_ipld_dagcbor.workspace = true
tokio.workspace = true
