[package]
name = "ceramic-anchor-service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
ceramic-anchor-tree.workspace = true
ceramic-anchor-tx.workspace = true
ceramic-core.workspace = true
cid.workspace = true
expect-test.workspace = true
hex.workspace = true
multihash-codetable.workspace = true
tokio.workspace = true
ring.workspace = true
