openapi: 3.0.0
info:
  description: >
    This is the Ceramic API for working with streams and events
  version: 0.16.0
  title: Ceramic API
  #license:
  #  name: Apache 2.0
  #  url: http://www.apache.org/licenses/LICENSE-2.0.html
  license:
    name: MIT
    url: https://mit-license.org/

servers:
  - url: /ceramic

paths:
  /liveness:
    get:
      summary: Test the liveness of the Ceramic node
      responses:
        "200":
          description: success
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /debug/heap:
    get:
      summary: Get the heap statistics of the Ceramic node
      responses:
        "200":
          description: success
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /version:
    post:
      summary: Get the version of the Ceramic node
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Version"
          description: success
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /events:
    post:
      summary: Creates a new event
      requestBody:
        $ref: "#/components/requestBodies/Event"
      responses:
        "204":
          description: success
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /events/{event_id}:
    get:
      summary: Get event data
      parameters:
        - name: event_id
          in: path
          description: identifier of the event
          schema:
            type: string
          required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestResponse"
        "404":
          description: Event not found
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  "/interests/{sort_key}/{sort_value}":
    post:
      summary: Register interest for a sort key
      parameters:
        - name: sort_key
          in: path
          description: name of the sort_key
          schema:
            type: string
          required: true
        - name: sort_value
          in: path
          description: value associated with the sort key
          schema:
            type: string
          required: true
        - name: controller
          in: query
          description: the controller to register interest for
          required: false
          schema:
            type: string
        - name: streamId
          in: query
          description: the stream to register interest for
          required: false
          schema:
            type: string
      responses:
        "204":
          description: success
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  "/interests":
    post:
      summary: Register interest for a sort key
      requestBody:
        $ref: "#/components/requestBodies/Interest"
      responses:
        "204":
          description: success
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  "/experimental/events/{sep}/{sepValue}":
    get:
      summary: Get events matching the interest stored on the node
      parameters:
        - name: sep
          in: path
          description: Name of the field in the Events header that holds the separator value e.g. 'model'
          schema:
            type: string
          required: true
        - name: sepValue
          in: path
          description: The value of the field in the Events header indicated by the separator key me.g. multibase encoded model ID
          schema:
            type: string
          required: true
        - name: controller
          in: query
          description: the controller to filter (DID string)
          required: false
          schema:
            type: string
        - name: streamId
          in: query
          description: the stream to filter (multibase encoded stream ID)
          required: false
          schema:
            type: string
        - name: offset
          in: query
          description: token that designates the point to resume from, that is find keys added after this point
          schema:
            type: integer
          required: false
        - name: limit
          in: query
          description: the maximum number of events to return, default is 10000.
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventsGet"
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  "/feed/events":
    get:
      summary: Get all new event keys since resume token
      parameters:
        - name: resumeAt
          in: query
          description: token that designates the point to resume from, that is find keys added after this point
          schema:
            type: string
          required: false
        - name: limit
          in: query
          description: the maximum number of events to return, default is 10000.
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventFeed"
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  requestBodies:
    Event:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Event"
      description: Event to add to the node
      required: true
    Message:
      content:
        application/cbor-seq:
          schema:
            format: byte
            type: string
      description: Recon message to send
      required: true
    Interest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Interest"
      description: Interest to register on the node
      required: true
  schemas:
    Version:
      description: Version of the Ceramic node in semver format, e.g. 2.1.0
      properties:
        version:
          type: string
          description: Version of the Ceramic node
    BadRequestResponse:
      title: Response to a bad request (400)
      description: Bad request (input error)
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Message describing the error
    Event:
      title: A Ceramic Event
      description: A Ceramic event as part of a Ceramic Stream
      type: object
      required:
        - id
        - data
      properties:
        id:
          type: string
          description: Multibase encoding of event root CID bytes.
        data:
          type: string
          description: Multibase encoding of event data.
    EventFeed:
      title: Ceramic Event feed data
      description: Ceramic event keys as part of a Ceramic Stream
      type: object
      required:
        - events
        - resumeToken
      properties:
        events:
          type: array
          items:
            schema:
            $ref: "#/components/schemas/Event"
          description: An array of events. For now, the value is empty.
        resumeToken:
          type: string
          description: The token/highwater mark to used as resumeAt on a future request
    EventsGet:
      title: Information about multiple events.
      description: Ceramic event keys as part of a Ceramic Stream
      type: object
      required:
        - events
        - resumeOffset
        - isComplete
      properties:
        events:
          type: array
          items:
            schema:
            $ref: "#/components/schemas/Event"
          description: An array of events
        resumeOffset:
          type: integer
          description: An integer specifying where to resume the request. Only works correctly for the same input parameters.
        isComplete:
          type: boolean
          description: A boolean specifying if there are more events to be fetched. Repeat with the resumeOffset to get next set.
    ErrorResponse:
      title: Error response
      description: Error response
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
    Interest:
      title: A recon interest
      description: Describes a recon interest range to store and synchronize
      type: object
      required:
        - sep
        - sepValue
      properties:
        sep:
          type: string
          description: Separator key, typically 'model' (sometimes called sort_key)
        sepValue:
          type: string
          description: Multibase encoded separator value (sometimes called sort_value, typically a stream ID)
        controller:
          type: string
          description: Decentralized identifier (DID) string
        streamId:
          type: string
          description: Multibase encoded stream ID.
