name: Deploy to Durable Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Durable environment to deploy to
        required: true
        options:
          - dev
          - qa
          - tnet
          - prod
      tag:
        type: string
        description: Tag to deploy
        required: true
        default: latest

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Schedule k8s deployment
        env:
          DEPLOY_ENV: ${{ github.event.inputs.environment }}
          DEPLOY_TAG: ${{ github.event.inputs.tag }}
        run: make schedule-k8s-deployment
