name: Deploy Image to Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Infrastructure environment to deploy to
        required: true
        default: dev
        options:
          - dev
          - qa
          - tnet
          - prod
      image_tag:
        type: string
        description: Image build tag to deploy
        required: true
        default: latest

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Schedule ECS deployment
        run: make DEPLOY_ENV="${{ matrix.network }}" DEPLOY_TARGET="custom" DEPLOY_TAG="${{ github.event.inputs.image_tag }}" schedule-deployment
