# Creates packages
name: Create Release and Pre-release

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release Type"
        required: true
        default: 'pre-release'
        type: choice
        options:
          - prerelease
          - release
      level:
        description: 'Pre-release level'
        required: false
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      # See https://github.com/3box/rust-builder
      image: public.ecr.aws/r5b3e0r5/3box/rust-builder:latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PAT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.email "github@3box.io"
          git config user.name "Github Automation"
      - run: npm install @openapitools/openapi-generator-cli@2.6.0 -g
      - name: Create release PR
        run: make RELEASE_LEVEL=${{ github.event.inputs.level }} RELEASE_TYPE=${{ github.event.inputs.release-type }} release-pr
