# Creates packages
name: Create Release PR

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Release level'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      # See https://github.com/3box/rust-builder
      image: public.ecr.aws/r5b3e0r5/3box/rust-builder:latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.email "github@3box.io"
          git config user.name "Github Automation"
      - name: Create release PR
        run: make RELEASE_LEVEL=${{ github.event.inputs.level }} release-pr
